### ISSUE TITLE
Firebase to Supabase Migration SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing

### ISSUE THREAD

**Issue by tiltmaster** [supabase-community/firebase-to-supabase#24]
Hi,

I am getting an error of 
`Error: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
    at parseServerFinalMessage (D:\supafirebase\firebase-to-supabase\node_modules\pg\lib\sasl.js:161:11)
    at Object.finalizeSession (D:\supafirebase\firebase-to-supabase\node_modules\pg\lib\sasl.js:72:31)
    at Client._handleAuthSASLFinal (D:\supafirebase\firebase-to-supabase\node_modules\pg\lib\client.js:262:10)
    at Connection.emit (node:events:513:28)
    at D:\supafirebase\firebase-to-supabase\node_modules\pg\lib\connection.js:114:12
    at Parser.parse (D:\supafirebase\firebase-to-supabase\node_modules\pg-protocol\dist\parser.js:40:17)
    at Socket.<anonymous> (D:\supafirebase\firebase-to-supabase\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)`

when running `node import_users.js user_dump.js 500` and im unable to import my firebase users, any help on this? i cant seem to find one discussion over this error.

**Comment by popmatik** [comment]
Did you fill out supabase.ts with your SUPABASE_URL and SUPABASE_KEY?

I think I remember seeing that error and I hadn't completed that file.
